/**
  Returns the libgit2 error message for the given error code.

  The error message represents the last error message generated by
  libgit2 in the current thread.

  :param: errorCode An error code returned by a libgit2 function.
  :returns: If the error message exists either in libgit2's thread-specific registry,
            or errno has been set by the system, this function returns the
            corresponding string representation of that error. Otherwise, it returns
            nil.
*/
internal func errorMessage(errorCode: Int32) -> String? {
  let last = giterr_last()
  if last != nil {
    return String.fromCString(last.memory.message)
  } else if UInt32(errorCode) == GITERR_OS.value {
    return String.fromCString(strerror(errno))
  } else {
    return nil
  }
}
